# Generated by Django 5.0.3 on 2024-03-27 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('asosiy', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('jins', models.CharField(max_length=10)),
                ('yosh', models.IntegerField()),
                ('daraja', models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr'), ('Doktorant', 'Doktorant'), ('Professor', 'Professor'), ('Oqituvchi', 'Oqituvchi')], max_length=20)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.fan')),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
                ('universitet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.universitet')),
            ],
        ),
        migrations.AddField(
            model_name='fan',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.yonalish'),
        ),
    ]
